import React, { useEffect, useState } from 'react'
import weatherContext from './weathercontext'

const WeatherState = (props) => {
    const [location, setLocation] = useState(null)
    const [current, setCurrent] = useState(null)
    const [forecast, setForecast] = useState(null)
    let weather_info ={
        "location": {
        "name": "Value",
        "region": "Mississippi",
        "country": "United States of America",
        "lat": 32.29,
        "lon": -90,
        "tz_id": "America/Chicago",
        "localtime_epoch": 1680593427,
        "localtime": "2023-04-04 2:30"
        },
        "current": {
        "last_updated_epoch": 1680593400,
        "last_updated": "2023-04-04 02:30",
        "temp_c": 23,
        "temp_f": 73.4,
        "is_day": 0,
        "condition": {
        "text": "clear",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
        "code": 1030
        },
        "wind_mph": 9.4,
        "wind_kph": 15.1,
        "wind_degree": 180,
        "wind_dir": "S",
        "pressure_mb": 1011,
        "pressure_in": 29.84,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 89,
        "cloud": 75,
        "feelslike_c": 25.2,
        "feelslike_f": 77.4,
        "vis_km": 9.7,
        "vis_miles": 6,
        "uv": 1,
        "gust_mph": 13.4,
        "gust_kph": 21.6
        },
        "forecast": {
        "forecastday": [
        {
        "date": "2023-04-04",
        "date_epoch": 1680566400,
        "day": {
        "maxtemp_c": 31.2,
        "maxtemp_f": 88.2,
        "mintemp_c": 21.6,
        "mintemp_f": 70.9,
        "avgtemp_c": 24.2,
        "avgtemp_f": 75.6,
        "maxwind_mph": 13.6,
        "maxwind_kph": 22,
        "totalprecip_mm": 0,
        "totalprecip_in": 0,
        "totalsnow_cm": 0,
        "avgvis_km": 9.3,
        "avgvis_miles": 5,
        "avghumidity": 80,
        "daily_will_it_rain": 0,
        "daily_chance_of_rain": 0,
        "daily_will_it_snow": 0,
        "daily_chance_of_snow": 0,
        "condition": {
        "text": "Overcast",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
        "code": 1009
        },
        "uv": 5
        },
        "astro": {
        "sunrise": "06:45 AM",
        "sunset": "07:23 PM",
        "moonrise": "06:10 PM",
        "moonset": "06:08 AM",
        "moon_phase": "Waxing Gibbous",
        "moon_illumination": "95",
        "is_moon_up": 1,
        "is_sun_up": 1
        },
        "hour": [
        {
        "time_epoch": 1680584400,
        "time": "2023-04-04 00:00",
        "temp_c": 22.9,
        "temp_f": 73.2,
        "is_day": 0,
        "condition": {
        "text": "Clear",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
        "code": 1000
        },
        "wind_mph": 7.6,
        "wind_kph": 12.2,
        "wind_degree": 188,
        "wind_dir": "S",
        "pressure_mb": 1010,
        "pressure_in": 29.83,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 80,
        "cloud": 10,
        "feelslike_c": 25,
        "feelslike_f": 77,
        "windchill_c": 22.9,
        "windchill_f": 73.2,
        "heatindex_c": 25,
        "heatindex_f": 77,
        "dewpoint_c": 19.3,
        "dewpoint_f": 66.7,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 15,
        "gust_kph": 24.1,
        "uv": 1
        },
        {
        "time_epoch": 1680588000,
        "time": "2023-04-04 01:00",
        "temp_c": 22,
        "temp_f": 71.6,
        "is_day": 0,
        "condition": {
        "text": "Partly cloudy",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
        "code": 1003
        },
        "wind_mph": 7.6,
        "wind_kph": 12.2,
        "wind_degree": 185,
        "wind_dir": "S",
        "pressure_mb": 1010,
        "pressure_in": 29.83,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 85,
        "cloud": 30,
        "feelslike_c": 24.5,
        "feelslike_f": 76.1,
        "windchill_c": 22,
        "windchill_f": 71.6,
        "heatindex_c": 24.5,
        "heatindex_f": 76.1,
        "dewpoint_c": 19.3,
        "dewpoint_f": 66.7,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 14.5,
        "gust_kph": 23.4,
        "uv": 1
        },
        {
        "time_epoch": 1680591600,
        "time": "2023-04-04 02:00",
        "temp_c": 21.4,
        "temp_f": 70.5,
        "is_day": 0,
        "condition": {
        "text": "Partly cloudy",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
        "code": 1003
        },
        "wind_mph": 7.2,
        "wind_kph": 11.5,
        "wind_degree": 183,
        "wind_dir": "S",
        "pressure_mb": 1010,
        "pressure_in": 29.84,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 89,
        "cloud": 49,
        "feelslike_c": 21.4,
        "feelslike_f": 70.5,
        "windchill_c": 21.4,
        "windchill_f": 70.5,
        "heatindex_c": 24.2,
        "heatindex_f": 75.6,
        "dewpoint_c": 19.5,
        "dewpoint_f": 67.1,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 13.4,
        "gust_kph": 21.6,
        "uv": 1
        },
        {
        "time_epoch": 1680595200,
        "time": "2023-04-04 03:00",
        "temp_c": 21.6,
        "temp_f": 70.9,
        "is_day": 0,
        "condition": {
        "text": "Overcast",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
        "code": 1009
        },
        "wind_mph": 6.7,
        "wind_kph": 10.8,
        "wind_degree": 176,
        "wind_dir": "S",
        "pressure_mb": 1010,
        "pressure_in": 29.83,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 91,
        "cloud": 100,
        "feelslike_c": 21.6,
        "feelslike_f": 70.9,
        "windchill_c": 21.6,
        "windchill_f": 70.9,
        "heatindex_c": 24.3,
        "heatindex_f": 75.7,
        "dewpoint_c": 20,
        "dewpoint_f": 68,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 2,
        "vis_miles": 1,
        "gust_mph": 12.3,
        "gust_kph": 19.8,
        "uv": 1
        },
        {
        "time_epoch": 1680598800,
        "time": "2023-04-04 04:00",
        "temp_c": 21.7,
        "temp_f": 71.1,
        "is_day": 0,
        "condition": {
        "text": "Overcast",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
        "code": 1009
        },
        "wind_mph": 7.4,
        "wind_kph": 11.9,
        "wind_degree": 174,
        "wind_dir": "S",
        "pressure_mb": 1011,
        "pressure_in": 29.84,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 92,
        "cloud": 100,
        "feelslike_c": 21.7,
        "feelslike_f": 71.1,
        "windchill_c": 21.7,
        "windchill_f": 71.1,
        "heatindex_c": 24.4,
        "heatindex_f": 75.9,
        "dewpoint_c": 20.3,
        "dewpoint_f": 68.5,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 0,
        "vis_miles": 0,
        "gust_mph": 12.5,
        "gust_kph": 20.2,
        "uv": 1
        },
        {
        "time_epoch": 1680602400,
        "time": "2023-04-04 05:00",
        "temp_c": 21.5,
        "temp_f": 70.7,
        "is_day": 0,
        "condition": {
        "text": "Overcast",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
        "code": 1009
        },
        "wind_mph": 7.2,
        "wind_kph": 11.5,
        "wind_degree": 172,
        "wind_dir": "S",
        "pressure_mb": 1011,
        "pressure_in": 29.85,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 93,
        "cloud": 100,
        "feelslike_c": 21.5,
        "feelslike_f": 70.7,
        "windchill_c": 21.5,
        "windchill_f": 70.7,
        "heatindex_c": 24.3,
        "heatindex_f": 75.7,
        "dewpoint_c": 20.4,
        "dewpoint_f": 68.7,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 0,
        "vis_miles": 0,
        "gust_mph": 11.9,
        "gust_kph": 19.1,
        "uv": 1
        },
        {
        "time_epoch": 1680606000,
        "time": "2023-04-04 06:00",
        "temp_c": 21.2,
        "temp_f": 70.2,
        "is_day": 0,
        "condition": {
        "text": "Overcast",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
        "code": 1009
        },
        "wind_mph": 8.3,
        "wind_kph": 13.3,
        "wind_degree": 179,
        "wind_dir": "S",
        "pressure_mb": 1011,
        "pressure_in": 29.87,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 95,
        "cloud": 100,
        "feelslike_c": 21.2,
        "feelslike_f": 70.2,
        "windchill_c": 21.2,
        "windchill_f": 70.2,
        "heatindex_c": 24.2,
        "heatindex_f": 75.6,
        "dewpoint_c": 20.4,
        "dewpoint_f": 68.7,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 13.4,
        "gust_kph": 21.6,
        "uv": 1
        },
        {
        "time_epoch": 1680609600,
        "time": "2023-04-04 07:00",
        "temp_c": 21.1,
        "temp_f": 70,
        "is_day": 1,
        "condition": {
        "text": "Overcast",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
        "code": 1009
        },
        "wind_mph": 9.4,
        "wind_kph": 15.1,
        "wind_degree": 180,
        "wind_dir": "S",
        "pressure_mb": 1012,
        "pressure_in": 29.88,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 96,
        "cloud": 100,
        "feelslike_c": 21.1,
        "feelslike_f": 70,
        "windchill_c": 21.1,
        "windchill_f": 70,
        "heatindex_c": 24.1,
        "heatindex_f": 75.4,
        "dewpoint_c": 20.4,
        "dewpoint_f": 68.7,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 13.9,
        "gust_kph": 22.3,
        "uv": 5
        },
        {
        "time_epoch": 1680613200,
        "time": "2023-04-04 08:00",
        "temp_c": 21.2,
        "temp_f": 70.2,
        "is_day": 1,
        "condition": {
        "text": "Overcast",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
        "code": 1009
        },
        "wind_mph": 10.5,
        "wind_kph": 16.9,
        "wind_degree": 183,
        "wind_dir": "S",
        "pressure_mb": 1012,
        "pressure_in": 29.89,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 94,
        "cloud": 100,
        "feelslike_c": 21.2,
        "feelslike_f": 70.2,
        "windchill_c": 21.2,
        "windchill_f": 70.2,
        "heatindex_c": 24.2,
        "heatindex_f": 75.6,
        "dewpoint_c": 20.2,
        "dewpoint_f": 68.4,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 15,
        "gust_kph": 24.1,
        "uv": 5
        },
        {
        "time_epoch": 1680616800,
        "time": "2023-04-04 09:00",
        "temp_c": 21.4,
        "temp_f": 70.5,
        "is_day": 1,
        "condition": {
        "text": "Overcast",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
        "code": 1009
        },
        "wind_mph": 9.8,
        "wind_kph": 15.8,
        "wind_degree": 176,
        "wind_dir": "S",
        "pressure_mb": 1013,
        "pressure_in": 29.91,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 91,
        "cloud": 100,
        "feelslike_c": 21.4,
        "feelslike_f": 70.5,
        "windchill_c": 21.4,
        "windchill_f": 70.5,
        "heatindex_c": 24.2,
        "heatindex_f": 75.6,
        "dewpoint_c": 19.9,
        "dewpoint_f": 67.8,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 13.2,
        "gust_kph": 21.2,
        "uv": 5
        },
        {
        "time_epoch": 1680620400,
        "time": "2023-04-04 10:00",
        "temp_c": 22,
        "temp_f": 71.6,
        "is_day": 1,
        "condition": {
        "text": "Overcast",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
        "code": 1009
        },
        "wind_mph": 11.9,
        "wind_kph": 19.1,
        "wind_degree": 175,
        "wind_dir": "S",
        "pressure_mb": 1013,
        "pressure_in": 29.91,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 88,
        "cloud": 100,
        "feelslike_c": 24.5,
        "feelslike_f": 76.1,
        "windchill_c": 22,
        "windchill_f": 71.6,
        "heatindex_c": 24.5,
        "heatindex_f": 76.1,
        "dewpoint_c": 19.8,
        "dewpoint_f": 67.6,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 13.9,
        "gust_kph": 22.3,
        "uv": 5
        },
        {
        "time_epoch": 1680624000,
        "time": "2023-04-04 11:00",
        "temp_c": 22.8,
        "temp_f": 73,
        "is_day": 1,
        "condition": {
        "text": "Overcast",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
        "code": 1009
        },
        "wind_mph": 13.2,
        "wind_kph": 21.2,
        "wind_degree": 177,
        "wind_dir": "S",
        "pressure_mb": 1013,
        "pressure_in": 29.91,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 85,
        "cloud": 99,
        "feelslike_c": 25,
        "feelslike_f": 77,
        "windchill_c": 22.8,
        "windchill_f": 73,
        "heatindex_c": 25,
        "heatindex_f": 77,
        "dewpoint_c": 20.1,
        "dewpoint_f": 68.2,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 15.2,
        "gust_kph": 24.5,
        "uv": 5
        },
        {
        "time_epoch": 1680627600,
        "time": "2023-04-04 12:00",
        "temp_c": 25.5,
        "temp_f": 77.9,
        "is_day": 1,
        "condition": {
        "text": "Overcast",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
        "code": 1009
        },
        "wind_mph": 13.6,
        "wind_kph": 22,
        "wind_degree": 179,
        "wind_dir": "S",
        "pressure_mb": 1012,
        "pressure_in": 29.88,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 75,
        "cloud": 92,
        "feelslike_c": 27.4,
        "feelslike_f": 81.3,
        "windchill_c": 25.5,
        "windchill_f": 77.9,
        "heatindex_c": 27.4,
        "heatindex_f": 81.3,
        "dewpoint_c": 20.7,
        "dewpoint_f": 69.3,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 15.7,
        "gust_kph": 25.2,
        "uv": 6
        },
        {
        "time_epoch": 1680631200,
        "time": "2023-04-04 13:00",
        "temp_c": 29.7,
        "temp_f": 85.5,
        "is_day": 1,
        "condition": {
        "text": "Sunny",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
        "code": 1000
        },
        "wind_mph": 13.9,
        "wind_kph": 22.3,
        "wind_degree": 180,
        "wind_dir": "S",
        "pressure_mb": 1012,
        "pressure_in": 29.87,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 67,
        "cloud": 6,
        "feelslike_c": 33.7,
        "feelslike_f": 92.7,
        "windchill_c": 29.7,
        "windchill_f": 85.5,
        "heatindex_c": 33.7,
        "heatindex_f": 92.7,
        "dewpoint_c": 22.9,
        "dewpoint_f": 73.2,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 15.9,
        "gust_kph": 25.6,
        "uv": 7
        },
        {
        "time_epoch": 1680634800,
        "time": "2023-04-04 14:00",
        "temp_c": 28.2,
        "temp_f": 82.8,
        "is_day": 1,
        "condition": {
        "text": "Partly cloudy",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
        "code": 1003
        },
        "wind_mph": 14.1,
        "wind_kph": 22.7,
        "wind_degree": 184,
        "wind_dir": "S",
        "pressure_mb": 1011,
        "pressure_in": 29.86,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 61,
        "cloud": 35,
        "feelslike_c": 30.1,
        "feelslike_f": 86.2,
        "windchill_c": 28.2,
        "windchill_f": 82.8,
        "heatindex_c": 30.1,
        "heatindex_f": 86.2,
        "dewpoint_c": 20,
        "dewpoint_f": 68,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 16.1,
        "gust_kph": 25.9,
        "uv": 7
        },
        {
        "time_epoch": 1680638400,
        "time": "2023-04-04 15:00",
        "temp_c": 28.1,
        "temp_f": 82.6,
        "is_day": 1,
        "condition": {
        "text": "Overcast",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
        "code": 1009
        },
        "wind_mph": 12.8,
        "wind_kph": 20.5,
        "wind_degree": 184,
        "wind_dir": "S",
        "pressure_mb": 1011,
        "pressure_in": 29.86,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 59,
        "cloud": 100,
        "feelslike_c": 29.8,
        "feelslike_f": 85.6,
        "windchill_c": 28.1,
        "windchill_f": 82.6,
        "heatindex_c": 29.8,
        "heatindex_f": 85.6,
        "dewpoint_c": 19.3,
        "dewpoint_f": 66.7,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 14.8,
        "gust_kph": 23.8,
        "uv": 6
        },
        {
        "time_epoch": 1680642000,
        "time": "2023-04-04 16:00",
        "temp_c": 27.9,
        "temp_f": 82.2,
        "is_day": 1,
        "condition": {
        "text": "Partly cloudy",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
        "code": 1003
        },
        "wind_mph": 11.6,
        "wind_kph": 18.7,
        "wind_degree": 184,
        "wind_dir": "S",
        "pressure_mb": 1011,
        "pressure_in": 29.85,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 59,
        "cloud": 53,
        "feelslike_c": 29.5,
        "feelslike_f": 85.1,
        "windchill_c": 27.9,
        "windchill_f": 82.2,
        "heatindex_c": 29.5,
        "heatindex_f": 85.1,
        "dewpoint_c": 19.2,
        "dewpoint_f": 66.6,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 14.3,
        "gust_kph": 23,
        "uv": 7
        },
        {
        "time_epoch": 1680645600,
        "time": "2023-04-04 17:00",
        "temp_c": 26.9,
        "temp_f": 80.4,
        "is_day": 1,
        "condition": {
        "text": "Cloudy",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
        "code": 1006
        },
        "wind_mph": 11.4,
        "wind_kph": 18.4,
        "wind_degree": 168,
        "wind_dir": "SSE",
        "pressure_mb": 1011,
        "pressure_in": 29.85,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 66,
        "cloud": 65,
        "feelslike_c": 28.7,
        "feelslike_f": 83.7,
        "windchill_c": 26.9,
        "windchill_f": 80.4,
        "heatindex_c": 28.7,
        "heatindex_f": 83.7,
        "dewpoint_c": 20.1,
        "dewpoint_f": 68.2,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 16.8,
        "gust_kph": 27,
        "uv": 6
        },
        {
        "time_epoch": 1680649200,
        "time": "2023-04-04 18:00",
        "temp_c": 26.2,
        "temp_f": 79.2,
        "is_day": 1,
        "condition": {
        "text": "Sunny",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
        "code": 1000
        },
        "wind_mph": 11.6,
        "wind_kph": 18.7,
        "wind_degree": 170,
        "wind_dir": "S",
        "pressure_mb": 1012,
        "pressure_in": 29.87,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 77,
        "cloud": 9,
        "feelslike_c": 28.6,
        "feelslike_f": 83.5,
        "windchill_c": 26.2,
        "windchill_f": 79.2,
        "heatindex_c": 28.6,
        "heatindex_f": 83.5,
        "dewpoint_c": 21.8,
        "dewpoint_f": 71.2,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 19.5,
        "gust_kph": 31.3,
        "uv": 7
        },
        {
        "time_epoch": 1680652800,
        "time": "2023-04-04 19:00",
        "temp_c": 24.6,
        "temp_f": 76.3,
        "is_day": 1,
        "condition": {
        "text": "Sunny",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
        "code": 1000
        },
        "wind_mph": 9.8,
        "wind_kph": 15.8,
        "wind_degree": 172,
        "wind_dir": "S",
        "pressure_mb": 1012,
        "pressure_in": 29.89,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 82,
        "cloud": 12,
        "feelslike_c": 26.7,
        "feelslike_f": 80.1,
        "windchill_c": 24.6,
        "windchill_f": 76.3,
        "heatindex_c": 26.7,
        "heatindex_f": 80.1,
        "dewpoint_c": 21.3,
        "dewpoint_f": 70.3,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 16.3,
        "gust_kph": 26.3,
        "uv": 6
        },
        {
        "time_epoch": 1680656400,
        "time": "2023-04-04 20:00",
        "temp_c": 23.9,
        "temp_f": 75,
        "is_day": 0,
        "condition": {
        "text": "Partly cloudy",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
        "code": 1003
        },
        "wind_mph": 10.3,
        "wind_kph": 16.6,
        "wind_degree": 160,
        "wind_dir": "SSE",
        "pressure_mb": 1012,
        "pressure_in": 29.87,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 68,
        "cloud": 47,
        "feelslike_c": 25.6,
        "feelslike_f": 78.1,
        "windchill_c": 23.9,
        "windchill_f": 75,
        "heatindex_c": 25.6,
        "heatindex_f": 78.1,
        "dewpoint_c": 17.7,
        "dewpoint_f": 63.9,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 17.7,
        "gust_kph": 28.4,
        "uv": 1
        },
        {
        "time_epoch": 1680660000,
        "time": "2023-04-04 21:00",
        "temp_c": 23.4,
        "temp_f": 74.1,
        "is_day": 0,
        "condition": {
        "text": "Cloudy",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
        "code": 1006
        },
        "wind_mph": 12.8,
        "wind_kph": 20.5,
        "wind_degree": 154,
        "wind_dir": "SSE",
        "pressure_mb": 1012,
        "pressure_in": 29.88,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 73,
        "cloud": 74,
        "feelslike_c": 25.3,
        "feelslike_f": 77.5,
        "windchill_c": 23.4,
        "windchill_f": 74.1,
        "heatindex_c": 25.3,
        "heatindex_f": 77.5,
        "dewpoint_c": 18.3,
        "dewpoint_f": 64.9,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 20.4,
        "gust_kph": 32.8,
        "uv": 1
        },
        {
        "time_epoch": 1680663600,
        "time": "2023-04-04 22:00",
        "temp_c": 22.6,
        "temp_f": 72.7,
        "is_day": 0,
        "condition": {
        "text": "Overcast",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
        "code": 1009
        },
        "wind_mph": 12.5,
        "wind_kph": 20.2,
        "wind_degree": 161,
        "wind_dir": "SSE",
        "pressure_mb": 1013,
        "pressure_in": 29.91,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 86,
        "cloud": 99,
        "feelslike_c": 24.9,
        "feelslike_f": 76.8,
        "windchill_c": 22.6,
        "windchill_f": 72.7,
        "heatindex_c": 24.9,
        "heatindex_f": 76.8,
        "dewpoint_c": 20.2,
        "dewpoint_f": 68.4,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 19.5,
        "gust_kph": 31.3,
        "uv": 1
        },
        {
        "time_epoch": 1680667200,
        "time": "2023-04-04 23:00",
        "temp_c": 22.6,
        "temp_f": 72.7,
        "is_day": 0,
        "condition": {
        "text": "Cloudy",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
        "code": 1006
        },
        "wind_mph": 11.6,
        "wind_kph": 18.7,
        "wind_degree": 163,
        "wind_dir": "SSE",
        "pressure_mb": 1013,
        "pressure_in": 29.91,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 80,
        "cloud": 66,
        "feelslike_c": 24.8,
        "feelslike_f": 76.6,
        "windchill_c": 22.6,
        "windchill_f": 72.7,
        "heatindex_c": 24.8,
        "heatindex_f": 76.6,
        "dewpoint_c": 19,
        "dewpoint_f": 66.2,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 17.7,
        "gust_kph": 28.4,
        "uv": 1
        }
        ]
        },
        {
        "date": "2023-04-05",
        "date_epoch": 1680652800,
        "day": {
        "maxtemp_c": 29.6,
        "maxtemp_f": 85.3,
        "mintemp_c": 20.1,
        "mintemp_f": 68.2,
        "avgtemp_c": 23.4,
        "avgtemp_f": 74.2,
        "maxwind_mph": 14.3,
        "maxwind_kph": 23,
        "totalprecip_mm": 2.3,
        "totalprecip_in": 0.09,
        "totalsnow_cm": 0,
        "avgvis_km": 9.8,
        "avgvis_miles": 6,
        "avghumidity": 81,
        "daily_will_it_rain": 1,
        "daily_chance_of_rain": 85,
        "daily_will_it_snow": 0,
        "daily_chance_of_snow": 0,
        "condition": {
        "text": "Patchy rain possible",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
        "code": 1063
        },
        "uv": 5
        },
        "astro": {
        "sunrise": "06:44 AM",
        "sunset": "07:23 PM",
        "moonrise": "07:08 PM",
        "moonset": "06:34 AM",
        "moon_phase": "Waxing Gibbous",
        "moon_illumination": "98",
        "is_moon_up": 1,
        "is_sun_up": 1
        },
        "hour": [
        {
        "time_epoch": 1680670800,
        "time": "2023-04-05 00:00",
        "temp_c": 22,
        "temp_f": 71.6,
        "is_day": 0,
        "condition": {
        "text": "Partly cloudy",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
        "code": 1003
        },
        "wind_mph": 11.2,
        "wind_kph": 18,
        "wind_degree": 165,
        "wind_dir": "SSE",
        "pressure_mb": 1013,
        "pressure_in": 29.91,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 82,
        "cloud": 48,
        "feelslike_c": 24.5,
        "feelslike_f": 76.1,
        "windchill_c": 22,
        "windchill_f": 71.6,
        "heatindex_c": 24.5,
        "heatindex_f": 76.1,
        "dewpoint_c": 18.9,
        "dewpoint_f": 66,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 17.4,
        "gust_kph": 28.1,
        "uv": 1
        },
        {
        "time_epoch": 1680674400,
        "time": "2023-04-05 01:00",
        "temp_c": 22.1,
        "temp_f": 71.8,
        "is_day": 0,
        "condition": {
        "text": "Overcast",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
        "code": 1009
        },
        "wind_mph": 10.5,
        "wind_kph": 16.9,
        "wind_degree": 165,
        "wind_dir": "SSE",
        "pressure_mb": 1013,
        "pressure_in": 29.93,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 84,
        "cloud": 100,
        "feelslike_c": 24.6,
        "feelslike_f": 76.3,
        "windchill_c": 22.1,
        "windchill_f": 71.8,
        "heatindex_c": 24.6,
        "heatindex_f": 76.3,
        "dewpoint_c": 19.2,
        "dewpoint_f": 66.6,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 16.6,
        "gust_kph": 26.6,
        "uv": 1
        },
        {
        "time_epoch": 1680678000,
        "time": "2023-04-05 02:00",
        "temp_c": 21.2,
        "temp_f": 70.2,
        "is_day": 0,
        "condition": {
        "text": "Overcast",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
        "code": 1009
        },
        "wind_mph": 9.6,
        "wind_kph": 15.5,
        "wind_degree": 172,
        "wind_dir": "S",
        "pressure_mb": 1014,
        "pressure_in": 29.93,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 90,
        "cloud": 100,
        "feelslike_c": 21.2,
        "feelslike_f": 70.2,
        "windchill_c": 21.2,
        "windchill_f": 70.2,
        "heatindex_c": 24.2,
        "heatindex_f": 75.6,
        "dewpoint_c": 19.4,
        "dewpoint_f": 66.9,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 15.2,
        "gust_kph": 24.5,
        "uv": 1
        },
        {
        "time_epoch": 1680681600,
        "time": "2023-04-05 03:00",
        "temp_c": 21.5,
        "temp_f": 70.7,
        "is_day": 0,
        "condition": {
        "text": "Overcast",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
        "code": 1009
        },
        "wind_mph": 9.6,
        "wind_kph": 15.5,
        "wind_degree": 176,
        "wind_dir": "S",
        "pressure_mb": 1014,
        "pressure_in": 29.93,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 89,
        "cloud": 100,
        "feelslike_c": 21.5,
        "feelslike_f": 70.7,
        "windchill_c": 21.5,
        "windchill_f": 70.7,
        "heatindex_c": 24.3,
        "heatindex_f": 75.7,
        "dewpoint_c": 19.6,
        "dewpoint_f": 67.3,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 14.8,
        "gust_kph": 23.8,
        "uv": 1
        },
        {
        "time_epoch": 1680685200,
        "time": "2023-04-05 04:00",
        "temp_c": 21.4,
        "temp_f": 70.5,
        "is_day": 0,
        "condition": {
        "text": "Overcast",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
        "code": 1009
        },
        "wind_mph": 9.8,
        "wind_kph": 15.8,
        "wind_degree": 177,
        "wind_dir": "S",
        "pressure_mb": 1013,
        "pressure_in": 29.91,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 87,
        "cloud": 100,
        "feelslike_c": 21.4,
        "feelslike_f": 70.5,
        "windchill_c": 21.4,
        "windchill_f": 70.5,
        "heatindex_c": 24.3,
        "heatindex_f": 75.7,
        "dewpoint_c": 19.1,
        "dewpoint_f": 66.4,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 15,
        "gust_kph": 24.1,
        "uv": 1
        },
        {
        "time_epoch": 1680688800,
        "time": "2023-04-05 05:00",
        "temp_c": 22.5,
        "temp_f": 72.5,
        "is_day": 0,
        "condition": {
        "text": "Partly cloudy",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
        "code": 1003
        },
        "wind_mph": 11.2,
        "wind_kph": 18,
        "wind_degree": 171,
        "wind_dir": "S",
        "pressure_mb": 1013,
        "pressure_in": 29.93,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 80,
        "cloud": 61,
        "feelslike_c": 24.8,
        "feelslike_f": 76.6,
        "windchill_c": 22.5,
        "windchill_f": 72.5,
        "heatindex_c": 24.8,
        "heatindex_f": 76.6,
        "dewpoint_c": 18.8,
        "dewpoint_f": 65.8,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 17.2,
        "gust_kph": 27.7,
        "uv": 1
        },
        {
        "time_epoch": 1680692400,
        "time": "2023-04-05 06:00",
        "temp_c": 22.5,
        "temp_f": 72.5,
        "is_day": 0,
        "condition": {
        "text": "Clear",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
        "code": 1000
        },
        "wind_mph": 12.5,
        "wind_kph": 20.2,
        "wind_degree": 166,
        "wind_dir": "SSE",
        "pressure_mb": 1013,
        "pressure_in": 29.93,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 79,
        "cloud": 16,
        "feelslike_c": 24.8,
        "feelslike_f": 76.6,
        "windchill_c": 22.5,
        "windchill_f": 72.5,
        "heatindex_c": 24.8,
        "heatindex_f": 76.6,
        "dewpoint_c": 18.6,
        "dewpoint_f": 65.5,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 19.5,
        "gust_kph": 31.3,
        "uv": 1
        },
        {
        "time_epoch": 1680696000,
        "time": "2023-04-05 07:00",
        "temp_c": 21,
        "temp_f": 69.8,
        "is_day": 1,
        "condition": {
        "text": "Overcast",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
        "code": 1009
        },
        "wind_mph": 11.9,
        "wind_kph": 19.1,
        "wind_degree": 169,
        "wind_dir": "S",
        "pressure_mb": 1014,
        "pressure_in": 29.95,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 91,
        "cloud": 100,
        "feelslike_c": 21,
        "feelslike_f": 69.8,
        "windchill_c": 21,
        "windchill_f": 69.8,
        "heatindex_c": 21,
        "heatindex_f": 69.8,
        "dewpoint_c": 19.4,
        "dewpoint_f": 66.9,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 19.2,
        "gust_kph": 31,
        "uv": 5
        },
        {
        "time_epoch": 1680699600,
        "time": "2023-04-05 08:00",
        "temp_c": 22.3,
        "temp_f": 72.1,
        "is_day": 1,
        "condition": {
        "text": "Partly cloudy",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
        "code": 1003
        },
        "wind_mph": 11.4,
        "wind_kph": 18.4,
        "wind_degree": 172,
        "wind_dir": "S",
        "pressure_mb": 1014,
        "pressure_in": 29.95,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 84,
        "cloud": 52,
        "feelslike_c": 24.7,
        "feelslike_f": 76.5,
        "windchill_c": 22.3,
        "windchill_f": 72.1,
        "heatindex_c": 24.7,
        "heatindex_f": 76.5,
        "dewpoint_c": 19.5,
        "dewpoint_f": 67.1,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 17,
        "gust_kph": 27.4,
        "uv": 6
        },
        {
        "time_epoch": 1680703200,
        "time": "2023-04-05 09:00",
        "temp_c": 23.4,
        "temp_f": 74.1,
        "is_day": 1,
        "condition": {
        "text": "Partly cloudy",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
        "code": 1003
        },
        "wind_mph": 13,
        "wind_kph": 20.9,
        "wind_degree": 166,
        "wind_dir": "SSE",
        "pressure_mb": 1014,
        "pressure_in": 29.93,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 80,
        "cloud": 42,
        "feelslike_c": 25.4,
        "feelslike_f": 77.7,
        "windchill_c": 23.4,
        "windchill_f": 74.1,
        "heatindex_c": 25.4,
        "heatindex_f": 77.7,
        "dewpoint_c": 19.8,
        "dewpoint_f": 67.6,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 17.2,
        "gust_kph": 27.7,
        "uv": 6
        },
        {
        "time_epoch": 1680706800,
        "time": "2023-04-05 10:00",
        "temp_c": 22.6,
        "temp_f": 72.7,
        "is_day": 1,
        "condition": {
        "text": "Overcast",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
        "code": 1009
        },
        "wind_mph": 13.2,
        "wind_kph": 21.2,
        "wind_degree": 174,
        "wind_dir": "S",
        "pressure_mb": 1016,
        "pressure_in": 30,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 82,
        "cloud": 100,
        "feelslike_c": 24.8,
        "feelslike_f": 76.6,
        "windchill_c": 22.6,
        "windchill_f": 72.7,
        "heatindex_c": 24.8,
        "heatindex_f": 76.6,
        "dewpoint_c": 19.3,
        "dewpoint_f": 66.7,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 15.9,
        "gust_kph": 25.6,
        "uv": 5
        },
        {
        "time_epoch": 1680710400,
        "time": "2023-04-05 11:00",
        "temp_c": 27.5,
        "temp_f": 81.5,
        "is_day": 1,
        "condition": {
        "text": "Sunny",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
        "code": 1000
        },
        "wind_mph": 13.4,
        "wind_kph": 21.6,
        "wind_degree": 182,
        "wind_dir": "S",
        "pressure_mb": 1015,
        "pressure_in": 29.97,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 67,
        "cloud": 17,
        "feelslike_c": 29.6,
        "feelslike_f": 85.3,
        "windchill_c": 27.5,
        "windchill_f": 81.5,
        "heatindex_c": 29.6,
        "heatindex_f": 85.3,
        "dewpoint_c": 20.7,
        "dewpoint_f": 69.3,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 15.4,
        "gust_kph": 24.8,
        "uv": 7
        },
        {
        "time_epoch": 1680714000,
        "time": "2023-04-05 12:00",
        "temp_c": 28.7,
        "temp_f": 83.7,
        "is_day": 1,
        "condition": {
        "text": "Partly cloudy",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
        "code": 1003
        },
        "wind_mph": 14.3,
        "wind_kph": 23,
        "wind_degree": 196,
        "wind_dir": "SSW",
        "pressure_mb": 1015,
        "pressure_in": 29.98,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 59,
        "cloud": 28,
        "feelslike_c": 30.6,
        "feelslike_f": 87.1,
        "windchill_c": 28.7,
        "windchill_f": 83.7,
        "heatindex_c": 30.6,
        "heatindex_f": 87.1,
        "dewpoint_c": 19.8,
        "dewpoint_f": 67.6,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 16.6,
        "gust_kph": 26.6,
        "uv": 7
        },
        {
        "time_epoch": 1680717600,
        "time": "2023-04-05 13:00",
        "temp_c": 25.3,
        "temp_f": 77.5,
        "is_day": 1,
        "condition": {
        "text": "Partly cloudy",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
        "code": 1003
        },
        "wind_mph": 11.9,
        "wind_kph": 19.1,
        "wind_degree": 204,
        "wind_dir": "SSW",
        "pressure_mb": 1016,
        "pressure_in": 30,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 75,
        "cloud": 37,
        "feelslike_c": 27.2,
        "feelslike_f": 81,
        "windchill_c": 25.3,
        "windchill_f": 77.5,
        "heatindex_c": 27.2,
        "heatindex_f": 81,
        "dewpoint_c": 20.6,
        "dewpoint_f": 69.1,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 9,
        "vis_miles": 5,
        "gust_mph": 14.1,
        "gust_kph": 22.7,
        "uv": 7
        },
        {
        "time_epoch": 1680721200,
        "time": "2023-04-05 14:00",
        "temp_c": 29.3,
        "temp_f": 84.7,
        "is_day": 1,
        "condition": {
        "text": "Thundery outbreaks possible",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/200.png",
        "code": 1087
        },
        "wind_mph": 11.6,
        "wind_kph": 18.7,
        "wind_degree": 197,
        "wind_dir": "SSW",
        "pressure_mb": 1015,
        "pressure_in": 29.96,
        "precip_mm": 0.1,
        "precip_in": 0,
        "humidity": 56,
        "cloud": 82,
        "feelslike_c": 31.2,
        "feelslike_f": 88.2,
        "windchill_c": 29.3,
        "windchill_f": 84.7,
        "heatindex_c": 31.2,
        "heatindex_f": 88.2,
        "dewpoint_c": 19.6,
        "dewpoint_f": 67.3,
        "will_it_rain": 1,
        "chance_of_rain": 81,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 9,
        "vis_miles": 5,
        "gust_mph": 13.4,
        "gust_kph": 21.6,
        "uv": 6
        },
        {
        "time_epoch": 1680724800,
        "time": "2023-04-05 15:00",
        "temp_c": 27.7,
        "temp_f": 81.9,
        "is_day": 1,
        "condition": {
        "text": "Light rain shower",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
        "code": 1240
        },
        "wind_mph": 10.1,
        "wind_kph": 16.2,
        "wind_degree": 204,
        "wind_dir": "SSW",
        "pressure_mb": 1015,
        "pressure_in": 29.96,
        "precip_mm": 0.3,
        "precip_in": 0.01,
        "humidity": 67,
        "cloud": 95,
        "feelslike_c": 30,
        "feelslike_f": 86,
        "windchill_c": 27.7,
        "windchill_f": 81.9,
        "heatindex_c": 30,
        "heatindex_f": 86,
        "dewpoint_c": 21,
        "dewpoint_f": 69.8,
        "will_it_rain": 1,
        "chance_of_rain": 89,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 12.8,
        "gust_kph": 20.5,
        "uv": 6
        },
        {
        "time_epoch": 1680728400,
        "time": "2023-04-05 16:00",
        "temp_c": 25.6,
        "temp_f": 78.1,
        "is_day": 1,
        "condition": {
        "text": "Overcast",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
        "code": 1009
        },
        "wind_mph": 8.5,
        "wind_kph": 13.7,
        "wind_degree": 204,
        "wind_dir": "SSW",
        "pressure_mb": 1016,
        "pressure_in": 29.99,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 75,
        "cloud": 100,
        "feelslike_c": 27.6,
        "feelslike_f": 81.7,
        "windchill_c": 25.6,
        "windchill_f": 78.1,
        "heatindex_c": 27.6,
        "heatindex_f": 81.7,
        "dewpoint_c": 20.9,
        "dewpoint_f": 69.6,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 13.6,
        "gust_kph": 22,
        "uv": 6
        },
        {
        "time_epoch": 1680732000,
        "time": "2023-04-05 17:00",
        "temp_c": 24.6,
        "temp_f": 76.3,
        "is_day": 1,
        "condition": {
        "text": "Light rain shower",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
        "code": 1240
        },
        "wind_mph": 7.4,
        "wind_kph": 11.9,
        "wind_degree": 208,
        "wind_dir": "SSW",
        "pressure_mb": 1015,
        "pressure_in": 29.98,
        "precip_mm": 0.8,
        "precip_in": 0.03,
        "humidity": 84,
        "cloud": 80,
        "feelslike_c": 26.8,
        "feelslike_f": 80.2,
        "windchill_c": 24.6,
        "windchill_f": 76.3,
        "heatindex_c": 26.8,
        "heatindex_f": 80.2,
        "dewpoint_c": 21.8,
        "dewpoint_f": 71.2,
        "will_it_rain": 0,
        "chance_of_rain": 63,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 12.1,
        "gust_kph": 19.4,
        "uv": 5
        },
        {
        "time_epoch": 1680735600,
        "time": "2023-04-05 18:00",
        "temp_c": 23.6,
        "temp_f": 74.5,
        "is_day": 1,
        "condition": {
        "text": "Light rain shower",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
        "code": 1240
        },
        "wind_mph": 5.6,
        "wind_kph": 9,
        "wind_degree": 206,
        "wind_dir": "SSW",
        "pressure_mb": 1016,
        "pressure_in": 29.99,
        "precip_mm": 0.8,
        "precip_in": 0.03,
        "humidity": 88,
        "cloud": 75,
        "feelslike_c": 25.8,
        "feelslike_f": 78.4,
        "windchill_c": 23.6,
        "windchill_f": 74.5,
        "heatindex_c": 25.8,
        "heatindex_f": 78.4,
        "dewpoint_c": 21.4,
        "dewpoint_f": 70.5,
        "will_it_rain": 1,
        "chance_of_rain": 80,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 10.3,
        "gust_kph": 16.6,
        "uv": 5
        },
        {
        "time_epoch": 1680739200,
        "time": "2023-04-05 19:00",
        "temp_c": 24.3,
        "temp_f": 75.7,
        "is_day": 1,
        "condition": {
        "text": "Overcast",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
        "code": 1009
        },
        "wind_mph": 5.1,
        "wind_kph": 8.3,
        "wind_degree": 175,
        "wind_dir": "S",
        "pressure_mb": 1016,
        "pressure_in": 29.99,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 79,
        "cloud": 100,
        "feelslike_c": 26.2,
        "feelslike_f": 79.2,
        "windchill_c": 24.3,
        "windchill_f": 75.7,
        "heatindex_c": 26.2,
        "heatindex_f": 79.2,
        "dewpoint_c": 20.5,
        "dewpoint_f": 68.9,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 7,
        "vis_miles": 4,
        "gust_mph": 9.6,
        "gust_kph": 15.5,
        "uv": 5
        },
        {
        "time_epoch": 1680742800,
        "time": "2023-04-05 20:00",
        "temp_c": 21.1,
        "temp_f": 70,
        "is_day": 0,
        "condition": {
        "text": "Light rain shower",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
        "code": 1240
        },
        "wind_mph": 4.5,
        "wind_kph": 7.2,
        "wind_degree": 198,
        "wind_dir": "SSW",
        "pressure_mb": 1017,
        "pressure_in": 30.02,
        "precip_mm": 0.8,
        "precip_in": 0.03,
        "humidity": 93,
        "cloud": 51,
        "feelslike_c": 21.1,
        "feelslike_f": 70,
        "windchill_c": 21.1,
        "windchill_f": 70,
        "heatindex_c": 24.1,
        "heatindex_f": 75.4,
        "dewpoint_c": 19.9,
        "dewpoint_f": 67.8,
        "will_it_rain": 1,
        "chance_of_rain": 79,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 9.4,
        "gust_kph": 15.1,
        "uv": 1
        },
        {
        "time_epoch": 1680746400,
        "time": "2023-04-05 21:00",
        "temp_c": 20.5,
        "temp_f": 68.9,
        "is_day": 0,
        "condition": {
        "text": "Light rain shower",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
        "code": 1240
        },
        "wind_mph": 4.3,
        "wind_kph": 6.8,
        "wind_degree": 255,
        "wind_dir": "WSW",
        "pressure_mb": 1018,
        "pressure_in": 30.05,
        "precip_mm": 1,
        "precip_in": 0.04,
        "humidity": 95,
        "cloud": 100,
        "feelslike_c": 20.5,
        "feelslike_f": 68.9,
        "windchill_c": 20.5,
        "windchill_f": 68.9,
        "heatindex_c": 20.5,
        "heatindex_f": 68.9,
        "dewpoint_c": 19.7,
        "dewpoint_f": 67.5,
        "will_it_rain": 1,
        "chance_of_rain": 79,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 8.7,
        "gust_kph": 14,
        "uv": 1
        },
        {
        "time_epoch": 1680750000,
        "time": "2023-04-05 22:00",
        "temp_c": 21.7,
        "temp_f": 71.1,
        "is_day": 0,
        "condition": {
        "text": "Partly cloudy",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
        "code": 1003
        },
        "wind_mph": 5.1,
        "wind_kph": 8.3,
        "wind_degree": 316,
        "wind_dir": "NW",
        "pressure_mb": 1017,
        "pressure_in": 30.03,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 87,
        "cloud": 32,
        "feelslike_c": 21.7,
        "feelslike_f": 71.1,
        "windchill_c": 21.7,
        "windchill_f": 71.1,
        "heatindex_c": 24.4,
        "heatindex_f": 75.9,
        "dewpoint_c": 19.5,
        "dewpoint_f": 67.1,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 7,
        "vis_miles": 4,
        "gust_mph": 8.3,
        "gust_kph": 13.3,
        "uv": 1
        },
        {
        "time_epoch": 1680753600,
        "time": "2023-04-05 23:00",
        "temp_c": 19.7,
        "temp_f": 67.5,
        "is_day": 0,
        "condition": {
        "text": "Light rain shower",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
        "code": 1240
        },
        "wind_mph": 5.4,
        "wind_kph": 8.6,
        "wind_degree": 340,
        "wind_dir": "NNW",
        "pressure_mb": 1019,
        "pressure_in": 30.08,
        "precip_mm": 0.6,
        "precip_in": 0.02,
        "humidity": 98,
        "cloud": 100,
        "feelslike_c": 19.7,
        "feelslike_f": 67.5,
        "windchill_c": 19.7,
        "windchill_f": 67.5,
        "heatindex_c": 19.7,
        "heatindex_f": 67.5,
        "dewpoint_c": 19.4,
        "dewpoint_f": 66.9,
        "will_it_rain": 0,
        "chance_of_rain": 60,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 8.5,
        "gust_kph": 13.7,
        "uv": 1
        }
        ]
        },
        {
        "date": "2023-04-06",
        "date_epoch": 1680739200,
        "day": {
        "maxtemp_c": 20.7,
        "maxtemp_f": 69.3,
        "mintemp_c": 10.7,
        "mintemp_f": 51.3,
        "avgtemp_c": 16.5,
        "avgtemp_f": 61.6,
        "maxwind_mph": 9.2,
        "maxwind_kph": 14.8,
        "totalprecip_mm": 9.7,
        "totalprecip_in": 0.38,
        "totalsnow_cm": 0,
        "avgvis_km": 7.8,
        "avgvis_miles": 4,
        "avghumidity": 94,
        "daily_will_it_rain": 1,
        "daily_chance_of_rain": 85,
        "daily_will_it_snow": 0,
        "daily_chance_of_snow": 0,
        "condition": {
        "text": "Moderate rain",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/302.png",
        "code": 1189
        },
        "uv": 4
        },
        "astro": {
        "sunrise": "06:42 AM",
        "sunset": "07:24 PM",
        "moonrise": "08:07 PM",
        "moonset": "07:01 AM",
        "moon_phase": "Full Moon",
        "moon_illumination": "100",
        "is_moon_up": 0,
        "is_sun_up": 1
        },
        "hour": [
        {
        "time_epoch": 1680757200,
        "time": "2023-04-06 00:00",
        "temp_c": 19.1,
        "temp_f": 66.4,
        "is_day": 0,
        "condition": {
        "text": "Light rain shower",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
        "code": 1240
        },
        "wind_mph": 5.4,
        "wind_kph": 8.6,
        "wind_degree": 357,
        "wind_dir": "N",
        "pressure_mb": 1019,
        "pressure_in": 30.08,
        "precip_mm": 0.5,
        "precip_in": 0.02,
        "humidity": 98,
        "cloud": 100,
        "feelslike_c": 19.1,
        "feelslike_f": 66.4,
        "windchill_c": 19.1,
        "windchill_f": 66.4,
        "heatindex_c": 19.1,
        "heatindex_f": 66.4,
        "dewpoint_c": 18.7,
        "dewpoint_f": 65.7,
        "will_it_rain": 1,
        "chance_of_rain": 84,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 8.5,
        "gust_kph": 13.7,
        "uv": 1
        },
        {
        "time_epoch": 1680760800,
        "time": "2023-04-06 01:00",
        "temp_c": 21.8,
        "temp_f": 71.2,
        "is_day": 0,
        "condition": {
        "text": "Cloudy",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
        "code": 1006
        },
        "wind_mph": 4.7,
        "wind_kph": 7.6,
        "wind_degree": 10,
        "wind_dir": "N",
        "pressure_mb": 1018,
        "pressure_in": 30.07,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 90,
        "cloud": 84,
        "feelslike_c": 21.8,
        "feelslike_f": 71.2,
        "windchill_c": 21.8,
        "windchill_f": 71.2,
        "heatindex_c": 24.4,
        "heatindex_f": 75.9,
        "dewpoint_c": 20,
        "dewpoint_f": 68,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 7.4,
        "gust_kph": 11.9,
        "uv": 1
        },
        {
        "time_epoch": 1680764400,
        "time": "2023-04-06 02:00",
        "temp_c": 18.8,
        "temp_f": 65.8,
        "is_day": 0,
        "condition": {
        "text": "Fog",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/248.png",
        "code": 1135
        },
        "wind_mph": 4.3,
        "wind_kph": 6.8,
        "wind_degree": 25,
        "wind_dir": "NNE",
        "pressure_mb": 1018,
        "pressure_in": 30.07,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 98,
        "cloud": 100,
        "feelslike_c": 18.8,
        "feelslike_f": 65.8,
        "windchill_c": 18.8,
        "windchill_f": 65.8,
        "heatindex_c": 18.8,
        "heatindex_f": 65.8,
        "dewpoint_c": 18.4,
        "dewpoint_f": 65.1,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 0,
        "vis_miles": 0,
        "gust_mph": 6.3,
        "gust_kph": 10.1,
        "uv": 1
        },
        {
        "time_epoch": 1680768000,
        "time": "2023-04-06 03:00",
        "temp_c": 18.6,
        "temp_f": 65.5,
        "is_day": 0,
        "condition": {
        "text": "Fog",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/248.png",
        "code": 1135
        },
        "wind_mph": 4.7,
        "wind_kph": 7.6,
        "wind_degree": 347,
        "wind_dir": "NNW",
        "pressure_mb": 1019,
        "pressure_in": 30.09,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 98,
        "cloud": 100,
        "feelslike_c": 18.6,
        "feelslike_f": 65.5,
        "windchill_c": 18.6,
        "windchill_f": 65.5,
        "heatindex_c": 18.6,
        "heatindex_f": 65.5,
        "dewpoint_c": 18.3,
        "dewpoint_f": 64.9,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 0,
        "vis_miles": 0,
        "gust_mph": 6.9,
        "gust_kph": 11.2,
        "uv": 1
        },
        {
        "time_epoch": 1680771600,
        "time": "2023-04-06 04:00",
        "temp_c": 21.5,
        "temp_f": 70.7,
        "is_day": 0,
        "condition": {
        "text": "Overcast",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
        "code": 1009
        },
        "wind_mph": 6.5,
        "wind_kph": 10.4,
        "wind_degree": 357,
        "wind_dir": "N",
        "pressure_mb": 1017,
        "pressure_in": 30.04,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 91,
        "cloud": 100,
        "feelslike_c": 21.5,
        "feelslike_f": 70.7,
        "windchill_c": 21.5,
        "windchill_f": 70.7,
        "heatindex_c": 24.3,
        "heatindex_f": 75.7,
        "dewpoint_c": 20,
        "dewpoint_f": 68,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 0,
        "vis_miles": 0,
        "gust_mph": 9.4,
        "gust_kph": 15.1,
        "uv": 1
        },
        {
        "time_epoch": 1680775200,
        "time": "2023-04-06 05:00",
        "temp_c": 16.6,
        "temp_f": 61.9,
        "is_day": 0,
        "condition": {
        "text": "Overcast",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
        "code": 1009
        },
        "wind_mph": 9.8,
        "wind_kph": 15.8,
        "wind_degree": 347,
        "wind_dir": "NNW",
        "pressure_mb": 1020,
        "pressure_in": 30.11,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 96,
        "cloud": 100,
        "feelslike_c": 16.6,
        "feelslike_f": 61.9,
        "windchill_c": 16.6,
        "windchill_f": 61.9,
        "heatindex_c": 16.6,
        "heatindex_f": 61.9,
        "dewpoint_c": 15.9,
        "dewpoint_f": 60.6,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 13.9,
        "gust_kph": 22.3,
        "uv": 1
        },
        {
        "time_epoch": 1680778800,
        "time": "2023-04-06 06:00",
        "temp_c": 15,
        "temp_f": 59,
        "is_day": 0,
        "condition": {
        "text": "Overcast",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
        "code": 1009
        },
        "wind_mph": 10.5,
        "wind_kph": 16.9,
        "wind_degree": 2,
        "wind_dir": "N",
        "pressure_mb": 1021,
        "pressure_in": 30.15,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 93,
        "cloud": 100,
        "feelslike_c": 13.9,
        "feelslike_f": 57,
        "windchill_c": 13.9,
        "windchill_f": 57,
        "heatindex_c": 15,
        "heatindex_f": 59,
        "dewpoint_c": 13.9,
        "dewpoint_f": 57,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 14.8,
        "gust_kph": 23.8,
        "uv": 1
        },
        {
        "time_epoch": 1680782400,
        "time": "2023-04-06 07:00",
        "temp_c": 20,
        "temp_f": 68,
        "is_day": 1,
        "condition": {
        "text": "Overcast",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
        "code": 1009
        },
        "wind_mph": 9.4,
        "wind_kph": 15.1,
        "wind_degree": 6,
        "wind_dir": "N",
        "pressure_mb": 1019,
        "pressure_in": 30.09,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 94,
        "cloud": 100,
        "feelslike_c": 20,
        "feelslike_f": 68,
        "windchill_c": 20,
        "windchill_f": 68,
        "heatindex_c": 20,
        "heatindex_f": 68,
        "dewpoint_c": 19,
        "dewpoint_f": 66.2,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 13.4,
        "gust_kph": 21.6,
        "uv": 5
        },
        {
        "time_epoch": 1680786000,
        "time": "2023-04-06 08:00",
        "temp_c": 14.8,
        "temp_f": 58.6,
        "is_day": 1,
        "condition": {
        "text": "Overcast",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
        "code": 1009
        },
        "wind_mph": 8.9,
        "wind_kph": 14.4,
        "wind_degree": 29,
        "wind_dir": "NNE",
        "pressure_mb": 1022,
        "pressure_in": 30.19,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 93,
        "cloud": 92,
        "feelslike_c": 13.9,
        "feelslike_f": 57,
        "windchill_c": 13.9,
        "windchill_f": 57,
        "heatindex_c": 14.8,
        "heatindex_f": 58.6,
        "dewpoint_c": 13.7,
        "dewpoint_f": 56.7,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 12.5,
        "gust_kph": 20.2,
        "uv": 3
        },
        {
        "time_epoch": 1680789600,
        "time": "2023-04-06 09:00",
        "temp_c": 15.7,
        "temp_f": 60.3,
        "is_day": 1,
        "condition": {
        "text": "Overcast",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
        "code": 1009
        },
        "wind_mph": 7.6,
        "wind_kph": 12.2,
        "wind_degree": 43,
        "wind_dir": "NE",
        "pressure_mb": 1023,
        "pressure_in": 30.2,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 92,
        "cloud": 89,
        "feelslike_c": 15.7,
        "feelslike_f": 60.3,
        "windchill_c": 15.7,
        "windchill_f": 60.3,
        "heatindex_c": 15.7,
        "heatindex_f": 60.3,
        "dewpoint_c": 14.3,
        "dewpoint_f": 57.7,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 10.3,
        "gust_kph": 16.6,
        "uv": 4
        },
        {
        "time_epoch": 1680793200,
        "time": "2023-04-06 10:00",
        "temp_c": 14.1,
        "temp_f": 57.4,
        "is_day": 1,
        "condition": {
        "text": "Overcast",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
        "code": 1009
        },
        "wind_mph": 6.9,
        "wind_kph": 11.2,
        "wind_degree": 28,
        "wind_dir": "NNE",
        "pressure_mb": 1022,
        "pressure_in": 30.18,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 93,
        "cloud": 100,
        "feelslike_c": 13.2,
        "feelslike_f": 55.8,
        "windchill_c": 13.2,
        "windchill_f": 55.8,
        "heatindex_c": 14.1,
        "heatindex_f": 57.4,
        "dewpoint_c": 12.9,
        "dewpoint_f": 55.2,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 8.7,
        "gust_kph": 14,
        "uv": 3
        },
        {
        "time_epoch": 1680796800,
        "time": "2023-04-06 11:00",
        "temp_c": 18,
        "temp_f": 64.4,
        "is_day": 1,
        "condition": {
        "text": "Overcast",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
        "code": 1009
        },
        "wind_mph": 9.4,
        "wind_kph": 15.1,
        "wind_degree": 16,
        "wind_dir": "NNE",
        "pressure_mb": 1024,
        "pressure_in": 30.25,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 85,
        "cloud": 100,
        "feelslike_c": 18,
        "feelslike_f": 64.4,
        "windchill_c": 18,
        "windchill_f": 64.4,
        "heatindex_c": 18,
        "heatindex_f": 64.4,
        "dewpoint_c": 15.5,
        "dewpoint_f": 59.9,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 10.7,
        "gust_kph": 17.3,
        "uv": 4
        },
        {
        "time_epoch": 1680800400,
        "time": "2023-04-06 12:00",
        "temp_c": 18.2,
        "temp_f": 64.8,
        "is_day": 1,
        "condition": {
        "text": "Overcast",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
        "code": 1009
        },
        "wind_mph": 8.7,
        "wind_kph": 14,
        "wind_degree": 29,
        "wind_dir": "NNE",
        "pressure_mb": 1024,
        "pressure_in": 30.25,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 83,
        "cloud": 100,
        "feelslike_c": 18.2,
        "feelslike_f": 64.8,
        "windchill_c": 18.2,
        "windchill_f": 64.8,
        "heatindex_c": 18.2,
        "heatindex_f": 64.8,
        "dewpoint_c": 15.3,
        "dewpoint_f": 59.5,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 10.3,
        "gust_kph": 16.6,
        "uv": 4
        },
        {
        "time_epoch": 1680804000,
        "time": "2023-04-06 13:00",
        "temp_c": 14.6,
        "temp_f": 58.3,
        "is_day": 1,
        "condition": {
        "text": "Overcast",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
        "code": 1009
        },
        "wind_mph": 7.8,
        "wind_kph": 12.6,
        "wind_degree": 43,
        "wind_dir": "NE",
        "pressure_mb": 1023,
        "pressure_in": 30.21,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 89,
        "cloud": 100,
        "feelslike_c": 13.3,
        "feelslike_f": 55.9,
        "windchill_c": 13.3,
        "windchill_f": 55.9,
        "heatindex_c": 14.6,
        "heatindex_f": 58.3,
        "dewpoint_c": 12.7,
        "dewpoint_f": 54.9,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 9.6,
        "gust_kph": 15.5,
        "uv": 3
        },
        {
        "time_epoch": 1680807600,
        "time": "2023-04-06 14:00",
        "temp_c": 20.4,
        "temp_f": 68.7,
        "is_day": 1,
        "condition": {
        "text": "Light rain shower",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
        "code": 1240
        },
        "wind_mph": 6.9,
        "wind_kph": 11.2,
        "wind_degree": 60,
        "wind_dir": "ENE",
        "pressure_mb": 1023,
        "pressure_in": 30.21,
        "precip_mm": 0.2,
        "precip_in": 0.01,
        "humidity": 79,
        "cloud": 100,
        "feelslike_c": 20.4,
        "feelslike_f": 68.7,
        "windchill_c": 20.4,
        "windchill_f": 68.7,
        "heatindex_c": 20.4,
        "heatindex_f": 68.7,
        "dewpoint_c": 16.6,
        "dewpoint_f": 61.9,
        "will_it_rain": 0,
        "chance_of_rain": 66,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 8.1,
        "gust_kph": 13,
        "uv": 5
        },
        {
        "time_epoch": 1680811200,
        "time": "2023-04-06 15:00",
        "temp_c": 21.7,
        "temp_f": 71.1,
        "is_day": 1,
        "condition": {
        "text": "Overcast",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
        "code": 1009
        },
        "wind_mph": 7.6,
        "wind_kph": 12.2,
        "wind_degree": 58,
        "wind_dir": "ENE",
        "pressure_mb": 1022,
        "pressure_in": 30.19,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 75,
        "cloud": 100,
        "feelslike_c": 21.7,
        "feelslike_f": 71.1,
        "windchill_c": 21.7,
        "windchill_f": 71.1,
        "heatindex_c": 24.4,
        "heatindex_f": 75.9,
        "dewpoint_c": 17,
        "dewpoint_f": 62.6,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 8.7,
        "gust_kph": 14,
        "uv": 5
        },
        {
        "time_epoch": 1680814800,
        "time": "2023-04-06 16:00",
        "temp_c": 13.1,
        "temp_f": 55.6,
        "is_day": 1,
        "condition": {
        "text": "Overcast",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
        "code": 1009
        },
        "wind_mph": 7.6,
        "wind_kph": 12.2,
        "wind_degree": 61,
        "wind_dir": "ENE",
        "pressure_mb": 1024,
        "pressure_in": 30.24,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 85,
        "cloud": 100,
        "feelslike_c": 11.4,
        "feelslike_f": 52.5,
        "windchill_c": 11.4,
        "windchill_f": 52.5,
        "heatindex_c": 13.1,
        "heatindex_f": 55.6,
        "dewpoint_c": 10.7,
        "dewpoint_f": 51.3,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 9.2,
        "gust_kph": 14.8,
        "uv": 3
        },
        {
        "time_epoch": 1680818400,
        "time": "2023-04-06 17:00",
        "temp_c": 21.9,
        "temp_f": 71.4,
        "is_day": 1,
        "condition": {
        "text": "Overcast",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
        "code": 1009
        },
        "wind_mph": 7.2,
        "wind_kph": 11.5,
        "wind_degree": 56,
        "wind_dir": "ENE",
        "pressure_mb": 1022,
        "pressure_in": 30.17,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 74,
        "cloud": 100,
        "feelslike_c": 21.9,
        "feelslike_f": 71.4,
        "windchill_c": 21.9,
        "windchill_f": 71.4,
        "heatindex_c": 24.5,
        "heatindex_f": 76.1,
        "dewpoint_c": 17.1,
        "dewpoint_f": 62.8,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 8.7,
        "gust_kph": 14,
        "uv": 5
        },
        {
        "time_epoch": 1680822000,
        "time": "2023-04-06 18:00",
        "temp_c": 20.7,
        "temp_f": 69.3,
        "is_day": 1,
        "condition": {
        "text": "Patchy rain possible",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
        "code": 1063
        },
        "wind_mph": 6.9,
        "wind_kph": 11.2,
        "wind_degree": 36,
        "wind_dir": "NE",
        "pressure_mb": 1022,
        "pressure_in": 30.18,
        "precip_mm": 0.1,
        "precip_in": 0,
        "humidity": 81,
        "cloud": 100,
        "feelslike_c": 20.7,
        "feelslike_f": 69.3,
        "windchill_c": 20.7,
        "windchill_f": 69.3,
        "heatindex_c": 20.7,
        "heatindex_f": 69.3,
        "dewpoint_c": 17.2,
        "dewpoint_f": 63,
        "will_it_rain": 1,
        "chance_of_rain": 78,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 8.9,
        "gust_kph": 14.4,
        "uv": 5
        },
        {
        "time_epoch": 1680825600,
        "time": "2023-04-06 19:00",
        "temp_c": 10.8,
        "temp_f": 51.4,
        "is_day": 1,
        "condition": {
        "text": "Light rain",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
        "code": 1183
        },
        "wind_mph": 6.9,
        "wind_kph": 11.2,
        "wind_degree": 41,
        "wind_dir": "NE",
        "pressure_mb": 1025,
        "pressure_in": 30.27,
        "precip_mm": 1,
        "precip_in": 0.04,
        "humidity": 94,
        "cloud": 96,
        "feelslike_c": 8.8,
        "feelslike_f": 47.8,
        "windchill_c": 8.8,
        "windchill_f": 47.8,
        "heatindex_c": 10.8,
        "heatindex_f": 51.4,
        "dewpoint_c": 9.8,
        "dewpoint_f": 49.6,
        "will_it_rain": 1,
        "chance_of_rain": 78,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 9.4,
        "gust_kph": 15.1,
        "uv": 3
        },
        {
        "time_epoch": 1680829200,
        "time": "2023-04-06 20:00",
        "temp_c": 17.5,
        "temp_f": 63.5,
        "is_day": 0,
        "condition": {
        "text": "Light rain shower",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
        "code": 1240
        },
        "wind_mph": 7.2,
        "wind_kph": 11.5,
        "wind_degree": 14,
        "wind_dir": "NNE",
        "pressure_mb": 1023,
        "pressure_in": 30.2,
        "precip_mm": 0.2,
        "precip_in": 0.01,
        "humidity": 89,
        "cloud": 83,
        "feelslike_c": 17.5,
        "feelslike_f": 63.5,
        "windchill_c": 17.5,
        "windchill_f": 63.5,
        "heatindex_c": 17.5,
        "heatindex_f": 63.5,
        "dewpoint_c": 15.7,
        "dewpoint_f": 60.3,
        "will_it_rain": 1,
        "chance_of_rain": 84,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 11.6,
        "gust_kph": 18.7,
        "uv": 1
        },
        {
        "time_epoch": 1680832800,
        "time": "2023-04-06 21:00",
        "temp_c": 17,
        "temp_f": 62.6,
        "is_day": 0,
        "condition": {
        "text": "Light rain shower",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
        "code": 1240
        },
        "wind_mph": 6.5,
        "wind_kph": 10.4,
        "wind_degree": 34,
        "wind_dir": "NE",
        "pressure_mb": 1023,
        "pressure_in": 30.22,
        "precip_mm": 0.3,
        "precip_in": 0.01,
        "humidity": 91,
        "cloud": 65,
        "feelslike_c": 17,
        "feelslike_f": 62.6,
        "windchill_c": 17,
        "windchill_f": 62.6,
        "heatindex_c": 17,
        "heatindex_f": 62.6,
        "dewpoint_c": 15.4,
        "dewpoint_f": 59.7,
        "will_it_rain": 0,
        "chance_of_rain": 64,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 10.1,
        "gust_kph": 16.2,
        "uv": 1
        },
        {
        "time_epoch": 1680836400,
        "time": "2023-04-06 22:00",
        "temp_c": 16.6,
        "temp_f": 61.9,
        "is_day": 0,
        "condition": {
        "text": "Light rain shower",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
        "code": 1240
        },
        "wind_mph": 6,
        "wind_kph": 9.7,
        "wind_degree": 22,
        "wind_dir": "NNE",
        "pressure_mb": 1024,
        "pressure_in": 30.23,
        "precip_mm": 1.1,
        "precip_in": 0.04,
        "humidity": 91,
        "cloud": 90,
        "feelslike_c": 16.6,
        "feelslike_f": 61.9,
        "windchill_c": 16.6,
        "windchill_f": 61.9,
        "heatindex_c": 16.6,
        "heatindex_f": 61.9,
        "dewpoint_c": 15.1,
        "dewpoint_f": 59.2,
        "will_it_rain": 0,
        "chance_of_rain": 52,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 8.7,
        "gust_kph": 14,
        "uv": 1
        },
        {
        "time_epoch": 1680840000,
        "time": "2023-04-06 23:00",
        "temp_c": 16.1,
        "temp_f": 61,
        "is_day": 0,
        "condition": {
        "text": "Light rain shower",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
        "code": 1240
        },
        "wind_mph": 6,
        "wind_kph": 9.7,
        "wind_degree": 17,
        "wind_dir": "NNE",
        "pressure_mb": 1024,
        "pressure_in": 30.24,
        "precip_mm": 0.4,
        "precip_in": 0.02,
        "humidity": 92,
        "cloud": 99,
        "feelslike_c": 16.1,
        "feelslike_f": 61,
        "windchill_c": 16.1,
        "windchill_f": 61,
        "heatindex_c": 16.1,
        "heatindex_f": 61,
        "dewpoint_c": 14.8,
        "dewpoint_f": 58.6,
        "will_it_rain": 0,
        "chance_of_rain": 70,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 8.5,
        "gust_kph": 13.7,
        "uv": 1
        }
        ]
        }
        ]
        }
        }
    

        useEffect(()=>{
            setCurrent(weather_info.current)
        setForecast(weather_info.forecast)
        setLocation(weather_info.location)
        },[])
    // let load = false
    function error() {
        document.getElementById("locating").innerHTML = "Unable to retrieve your location";
      }
    // function getLocation() {
    //     if (navigator.geolocation) {
    //         navigator.geolocation.getCurrentPosition(getWeather,error)
    //     } else {
    //         document.getElementById("locating").innerHTML="Geolocation is not supported by this browser."
    //     }
    // }
    // const getWeather = async (position) => {
    //     try {
    //         document.getElementById("locating").innerHTML=""
    //     const url = `https://api.weatherapi.com/v1/forecast.json?key=12e425f865dd4179ad7165926230204&q=${position.coords.latitude},${position.coords.longitude}&days=3&aqi=no&alerts=no`
    //     const data = await fetch(url);
    //     const parsedData = await data.json()
    //     setLocation(parsedData.location);
    //     setCurrent(parsedData.current)
    //     setForecast(parsedData.forecast)
            
    //     } catch (error) {
    //         document.getElementById("locating").innerHTML=error
    //     }
    //     // console.log(parsedData.current)
    // }
    // // console.log(location)
    // const handleSearch=async (e)=>{
    //     e.preventDefault()
    //     let value=document.getElementById("search").value
    //     const url = `https://api.weatherapi.com/v1/forecast.json?key=12e425f865dd4179ad7165926230204&q=${value}&days=3&aqi=no&alerts=no`
    //     const data = await fetch(url);
    //     const parsedData = await data.json()
    //     setLocation(parsedData.location);
    //     setCurrent(parsedData.current)
    //     setForecast(parsedData.forecast)
    // }
    const setBackground=(current)=>{
        if(current.condition.text==="Sunny"){
        document.body.style.backgroundImage=`url("https://wallpapers.com/images/hd/sunny-weather-with-cherry-blossom-fr2tn0f21evp0viw.jpg")`
        }
        else if(current.condition.text==="Mist"){
            document.body.style.backgroundImage='url("https://e0.pxfuel.com/wallpapers/978/224/desktop-wallpaper-foggy-weather-foggy.jpg")'
        }
        else if(current.condition.text==="Clear"){
            document.body.style.backgroundImage='url("https://i.gifer.com/Lx0q.gif")'
        }
        else if(current.condition.text==="Cloudy"){
            document.body.style.backgroundImage='url("https://i.gifer.com/LSzq.gif")'
        }
        else if(current.condition.text==="Heavy rain"){
            document.body.style.backgroundImage='url("https://images.pexels.com/photos/9105781/pexels-photo-9105781.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1")'
        }
        else if(current.condition.text==="Light rain"){
            document.body.style.backgroundImage='url("https://images.pexels.com/photos/459451/pexels-photo-459451.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1")'
        }
        else if(current.condition.text==="Partly cloudy"){
            document.body.style.backgroundImage='url("https://english.wafa.ps/image/NewsThumbImg/Default/d5a2271e-bc63-444a-9125-e94e6a6cbf04.jpeg")'
        }
        else{
            document.body.style.backgroundImage='url("https://images.pexels.com/photos/1118873/pexels-photo-1118873.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1")'
        }
    }
    return (
        // <weatherContext.Provider value={{ location, current, forecast, getWeather,getLocation,handleSearch }}>
        <weatherContext.Provider value={{ location, current, forecast,setBackground }}>
            {props.children}
        </weatherContext.Provider>
    )
}

export default WeatherState
